### ISSUE TITLE
Results of fuzzing your application.

### ISSUE THREAD

**Issue by NeverMine17** [whr4935/huffman_encode_decode#1]
After around 10 minutes of fuzzing using american fuzzy lop, i have found 24 unique crashes!
Results attached in `.tar.gz` format.
@whr4935 , hope you fix it!

**Comment by whr4935** [comment]
Hi NeverMine17，how to correct use afl-fuzz， what's  the  -f option mean? 

afl-fuzz -i input/ -o output/ -f ./input.huf -- ./h_dec ./input.huf

**Comment by NeverMine17** [comment]
> `afl-fuzz -i input/ -o output/ -f ./input.huf -- ./h_dec ./input.huf`

One of the testcases from folder `input/` get written to `input.huf` and program `h_dec` decodes `input.huf`.
<details> 
  <summary>Full help from afl-fuzz</summary>
afl-fuzz [ options ] -- /path/to/fuzzed_app [ ... ]

Required parameters:

  -i dir        - input directory with test cases
  -o dir        - output directory for fuzzer findings

Execution control settings:

  -f file       - location read by the fuzzed program (stdin)
  -t msec       - timeout for each run (auto-scaled, 50-1000 ms)
  -m megs       - memory limit for child process (50 MB)
  -Q            - use binary-only instrumentation (QEMU mode)

Fuzzing behavior settings:

  -d            - quick & dirty mode (skips deterministic steps)
  -n            - fuzz without instrumentation (dumb mode)
  -x dir        - optional fuzzer dictionary (see README)

Other stuff:

  -T text       - text banner to show on the screen
  -M / -S id    - distributed mode (see parallel_fuzzing.txt)
  -C            - crash exploration mode (the peruvian rabbit thing)
</details>

**Comment by NeverMine17** [comment]
Ping @whr4935
